spring.application.name=inventory-service



# 2. Thông tin k?t n?i Database
# localhost:5432 là ??a ch? máy bro, n?i Docker ?ang m? c?ng
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_service
spring.datasource.username=devops
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. C?u hình JPA (T? ??ng t?o b?ng Database)
# update: T? ??ng c?p nh?t c?u trúc b?ng khi bro s?a code (Ti?n cho dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect