name: DevSecOps Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code về
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Chạy unit test ( bước bắt buộc)
      # Nếu như fail -> dừng , không build nữa
      - name: Run Unit Tests
        run: |
          chmod +x mvnw
          ./mvnw test 
      
      # 4. Build file .jar
      - name: Build application
        run: ./mvnw clean package

      # 5. Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Build image để scan bằng Trivy
      - name: Build Docker Image for Scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Load image vào local runner
          tags: ${{ secrets.DOCKER_USERNAME }}/inventory-service:${{ github.sha }}

      # 8. Scan lỗ hổng bằng Trivy
      # Scan ở mức độ CRITICAL & HIGH. Nếu có lỗ hổng CRITICAL thì sẽ fail pipeline
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/inventory-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Lỗi 1 nếu phát hiện có lỗi -> Dừng pipeline lại
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      #9. Push Docker Image ( sau khi qua Test và Security )
      # Push 2 tags: Mã commit (để truy vết) và Latest (để deploy)
      - name: Push Docker Image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/inventory-service:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest